version: '3.9'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD}
    ports:
      - 8000:8000
    env_file:
      - ${PWD}/eventify/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: eventify # Jméno uživatele databáze
      POSTGRES_PASSWORD: eventify # Helslo uživatele databáze
      POSTGRES_DB: eventify # Jméno databáze