# Generated by Django 5.0.3 on 2024-06-11 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 11, 7, 12, 26, 24744, tzinfo=datetime.timezone.utc), help_text='Zadejte čas konce eventu', verbose_name='Čas konce eventu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 11, 7, 12, 26, 24744, tzinfo=datetime.timezone.utc), help_text='Zadejte čas začátku eventu', verbose_name='Čas začátku eventu'),
        ),
    ]
