# Generated by Django 5.0.3 on 2024-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name_on_card',
            field=models.TextField(default=''),
        ),
    ]
