# Generated by Django 5.0.3 on 2024-11-08 11:10

import django.db.models.deletion
import eventify_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0002_paymentmethod_name_on_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adresa', 'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Košík', 'verbose_name_plural': 'Košíky'},
        ),
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name': 'Doručovací adresa', 'verbose_name_plural': 'Doručovací adresy'},
        ),
        migrations.AlterModelOptions(
            name='eventaddress',
            options={'verbose_name': 'Adresa události', 'verbose_name_plural': 'Adresy událostí'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Platební metoda', 'verbose_name_plural': 'Platební metody'},
        ),
        migrations.AlterModelOptions(
            name='ticketpurchase',
            options={'verbose_name': 'Nákup vstupenky', 'verbose_name_plural': 'Nákupy vstupenek'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Typ vstupenky', 'verbose_name_plural': 'Typy vstupenek'},
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='country',
            field=models.CharField(default='Česká republika', help_text='Zadejte stát', max_length=255, verbose_name='Stát'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Zadejte počet vstupenek v košíku', verbose_name='Počet vstupenek'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Zadejte celkovou částku', max_digits=10, verbose_name='Celková částka'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.TextField(help_text='Zadejte město', verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Zadejte číslo popisné', verbose_name='Číslo popisné'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.TextField(help_text='Zadejte PSČ', verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='street',
            field=models.TextField(help_text='Zadejte ulici', verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.TextField(help_text='Zadejte 16místné číslo karty.', max_length=16, validators=[eventify_app.models.validate_card_number], verbose_name='Číslo karty'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cvv',
            field=models.TextField(help_text='Bezpečnostní kód na zadní straně karty.', max_length=3, validators=[eventify_app.models.validate_cvv], verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_date',
            field=models.DateField(help_text='Datum expirace karty ve formátu MM/RR.', validators=[eventify_app.models.validate_expiration_date], verbose_name='Datum expirace'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name_on_card',
            field=models.TextField(default='', help_text='Jméno, které je uvedeno na kartě.', max_length=255, verbose_name='Jméno na kartě'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(help_text='Uživatel, který tuto platební metodu vlastní.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Zadejte počet zakoupených vstupenek', verbose_name='Počet zakoupených vstupenek'),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Zadejte celkovou částku', max_digits=10, verbose_name='Celková částka'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(help_text='Zadejte název vstupenky', max_length=255, verbose_name='Název vstupenky'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Zadejte cenu vstupenky', max_digits=8, verbose_name='Cena vstupenky'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity',
            field=models.IntegerField(help_text='Zadejte počet vstupenek', verbose_name='Počet vstupenek'),
        ),
    ]
