# Generated by Django 5.0.3 on 2024-09-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0002_event_organization'),
        ('eventify_app', '0003_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
    ]
