# Generated by Django 5.0.3 on 2024-11-09 12:49

import eventify_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0003_alter_address_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_date',
            field=models.DateField(help_text='Datum expirace karty ve formátu MM/RR.', null=True, validators=[eventify_app.models.validate_expiration_date], verbose_name='Datum expirace'),
        ),
    ]
