# Generated by Django 5.0.3 on 2024-09-22 06:59

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0004_merge_20240921_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seats',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, help_text='Zadejte telefonní číslo', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Telefonní číslo musí obsahovat přesně 9 číslic.', regex='^\\d{9}$')], verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 22, 6, 59, 1, 650676, tzinfo=datetime.timezone.utc), help_text='Zadejte čas konce eventu', verbose_name='Čas konce eventu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(error_messages={'null': 'Nejsi v organizaci nemůžeš vytvořit event!'}, help_text='Vyberte organizaci', null=True, on_delete=django.db.models.deletion.CASCADE, to='eventify_app.organization', verbose_name='Organizace'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 22, 6, 59, 1, 650563, tzinfo=datetime.timezone.utc), help_text='Zadejte čas začátku eventu', verbose_name='Čas začátku eventu'),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název vstupenky')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena vstupenky')),
                ('quantity', models.IntegerField(verbose_name='Počet vstupenek')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='eventify_app.event')),
            ],
        ),
    ]
