# Generated by Django 5.0.3 on 2024-11-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0004_alter_paymentmethod_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('card', 'Karta'), ('paypal', 'PayPal'), ('cash', 'Hotově'), ('bank_transfer', 'Bankovním převodem')], help_text='Zvolte typ platby.', verbose_name='Typ platby')),
                ('user', models.ForeignKey(help_text='Uživatel, který tuto platební metodu vlastní.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
        ),
    ]
