# Generated by Django 5.0.3 on 2024-11-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0005_paymethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymethod',
            name='user',
        ),
        migrations.AddField(
            model_name='paymethod',
            name='cart',
            field=models.ForeignKey(default=None, help_text='Košík pro, který tato platební metoda platí.', on_delete=django.db.models.deletion.CASCADE, to='eventify_app.cart', verbose_name='Košík'),
        ),
    ]
