# Generated by Django 5.0.3 on 2024-11-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0006_remove_paymethod_user_paymethod_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymethod',
            name='cart',
        ),
        migrations.AddField(
            model_name='paymethod',
            name='user',
            field=models.ForeignKey(default=None, help_text='Uživatel pro, kterého tento košík platí.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
    ]
