# Generated by Django 5.0.3 on 2024-11-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0007_remove_paymethod_cart_paymethod_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayMethod',
        ),
    ]
