# Generated by Django 5.0.3 on 2024-11-13 12:29

import django.db.models.deletion
import eventify_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0008_delete_paymethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventaddress',
            options={'verbose_name': 'Adresa Eventu', 'verbose_name_plural': 'Adresa Eventu'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='eventaddress',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Zadejte číslo popisné', null=True, verbose_name='Číslo popisné'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.TextField(help_text='Zadejte PSČ', validators=[eventify_app.models.validate_postal_code], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='eventaddress',
            name='city',
            field=models.TextField(help_text='Zadejte město', verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='eventaddress',
            name='country',
            field=models.CharField(default='Česká republika', help_text='Zadejte stát', max_length=255, verbose_name='Stát'),
        ),
        migrations.AlterField(
            model_name='eventaddress',
            name='postal_code',
            field=models.TextField(help_text='Zadejte PSČ', validators=[eventify_app.models.validate_postal_code], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='eventaddress',
            name='street',
            field=models.TextField(help_text='Zadejte ulici', verbose_name='Ulice'),
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(help_text='Zadejte ulici', verbose_name='Ulice')),
                ('number', models.PositiveSmallIntegerField(blank=True, help_text='Zadejte číslo popisné', null=True, verbose_name='Číslo popisné')),
                ('city', models.TextField(help_text='Zadejte město', verbose_name='Město')),
                ('postal_code', models.TextField(help_text='Zadejte PSČ', validators=[eventify_app.models.validate_postal_code], verbose_name='PSČ')),
                ('country', models.CharField(default='Česká republika', help_text='Zadejte stát', max_length=255, verbose_name='Stát')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventify_app.organization')),
            ],
            options={
                'verbose_name': 'Adresa Organizace',
                'verbose_name_plural': 'Adresa Organizace',
            },
        ),
    ]
