# Generated by Django 5.0.3 on 2024-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0009_alter_eventaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
