# Generated by Django 5.0.3 on 2024-11-15 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0010_eventaddress_latitude_eventaddress_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Zadejte čas konání eventu', verbose_name='Čas konání eventu'),
        ),
    ]
