# Generated by Django 5.0.3 on 2024-11-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0011_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Konference'), ('festival', 'Festival'), ('workshop', 'Workshop'), ('sport', 'Sportovní událost'), ('social', 'Společenská akce'), ('exhibition', 'Výstava'), ('concert', 'Koncert'), ('online', 'Online událost'), ('local', 'Městská akce')], default='conference', max_length=20),
        ),
    ]
