# Generated by Django 5.0.3 on 2024-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0015_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
