# Generated by Django 5.0.3 on 2024-10-07 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0017_ticketpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum vytvoření'),
        ),
        migrations.DeleteModel(
            name='UserEventRegistration',
        ),
    ]
