# Generated by Django 5.0.3 on 2024-10-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0018_ticketpurchase_date_delete_usereventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='left',
            field=models.IntegerField(default=0, editable=False, verbose_name='Počet zbývajících vstupenek'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventify_app.event'),
        ),
    ]
