# Generated by Django 5.0.3 on 2024-10-11 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0019_tickettype_left_alter_tickettype_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_birth',
            field=models.DateField(default='2000-01-01', help_text='Zadejte datum narození', verbose_name='Datum narození'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, help_text='Vyberte obrázek uživatele', null=True, upload_to='user_images/', verbose_name='Obrázek uživatele'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Zadejte ulici', max_length=255, verbose_name='Ulice')),
                ('city', models.CharField(help_text='Zadejte město', max_length=255, verbose_name='Město')),
                ('postal_code', models.CharField(help_text='Zadejte PSČ', max_length=6, verbose_name='PSČ')),
                ('country', models.CharField(help_text='Zadejte zemi', max_length=255, verbose_name='Země')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
