# Generated by Django 5.0.3 on 2024-10-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_app', '0020_customuser_date_birth_customuser_image_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Zadejte ulici', max_length=255, verbose_name='Ulice')),
                ('city', models.CharField(help_text='Zadejte město', max_length=255, verbose_name='Město')),
                ('postal_code', models.CharField(help_text='Zadejte PSČ', max_length=6, verbose_name='PSČ')),
                ('country', models.CharField(help_text='Zadejte zemi', max_length=255, verbose_name='Země')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventify_app.event')),
            ],
        ),
    ]
